import { useEffect, useMemo, useState } from 'react';

const regions={
  Northeast:{city:'New York, NY',coords:[40.7128,-74.006],weather:'Winter storms',score:61,road:'Elevated',action:'Build a winter kit'},
  Southeast:{city:'Atlanta, GA',coords:[33.749,-84.388],weather:'Hurricanes & flooding',score:82,road:'High during storms',action:'Plan an evacuation route'},
  Midwest:{city:'Chicago, IL',coords:[41.8781,-87.6298],weather:'Tornadoes & ice',score:72,road:'Variable',action:'Watch changing forecasts'},
  Southwest:{city:'Phoenix, AZ',coords:[33.4484,-112.074],weather:'Heat & flash floods',score:79,road:'Heat-related',action:'Carry extra water'},
  West:{city:'Los Angeles, CA',coords:[34.0522,-118.2437],weather:'Wildfires & earthquakes',score:84,road:'Elevated',action:'Make a go-bag'}
};
const riskData=[
  ['Northeast','Coastal storms, nor’easters, and winter weather.',[['New York',[['Winter Storm','High'],['Flood','Moderate']],[['New York City','Coastal flooding and nor’easters.',[['Flood','High'],['Hurricane','Moderate']]],['Buffalo','Lake-effect snow events.',[['Winter Storm','Severe']]]]],['Massachusetts',[['Winter Storm','High'],['Flood','Moderate']],[['Boston','Coastal storm surge and winter weather.',[['Winter Storm','High'],['Hurricane','Moderate']]]]]]],
  ['Southeast','Tropical systems, flooding, and severe thunderstorms.',[['Florida',[['Hurricane','Severe'],['Flood','High']],[['Miami','Hurricane, storm-surge, and flooding exposure.',[['Hurricane','Severe'],['Flood','Severe']]],['Tampa','Storm-surge vulnerability.',[['Hurricane','Severe'],['Flood','High']]]]],['Louisiana',[['Hurricane','Severe'],['Flood','Severe']],[['New Orleans','Levee-dependent flood protection.',[['Hurricane','Severe'],['Flood','Severe']]]]]]],
  ['Midwest','Tornado Alley overlap and winter weather.',[['Kansas',[['Tornado','Severe'],['Winter Storm','Moderate']],[['Wichita','Severe storms and tornadoes.',[['Tornado','Severe']]]]],['Illinois',[['Tornado','High'],['Winter Storm','High']],[['Chicago','Lake-effect snow and winter storms.',[['Winter Storm','High'],['Tornado','Moderate']]]]]]],
  ['Southwest','Wildfire, extreme heat, drought, and flash flooding.',[['Arizona',[['Wildfire','High'],['Flood','Moderate']],[['Phoenix','Extreme heat and monsoon flash flooding.',[['Flood','Moderate'],['Wildfire','Moderate']]]]],['Texas',[['Hurricane','High'],['Tornado','High'],['Flood','High']],[['Houston','Hurricane and flash-flood exposure.',[['Hurricane','Severe'],['Flood','Severe']]]]]]],
  ['West','Wildfire, earthquake, and drought stress.',[['California',[['Wildfire','Severe'],['Earthquake','Severe']],[['Los Angeles','Wildfire-urban interface and fault-line risk.',[['Wildfire','Severe'],['Earthquake','High']]],['San Francisco','Hayward and San Andreas fault exposure.',[['Earthquake','Severe'],['Wildfire','Moderate']]]]],['Washington',[['Earthquake','High'],['Flood','Moderate']],[['Seattle','Cascadia earthquake and flooding risk.',[['Earthquake','High'],['Flood','Moderate']]]]]]]
];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);

function Badge({risk}){return <span className={`badge ${risk[1].toLowerCase()}`}>{risk[0]} · {risk[1]}</span>}
function RiskNavigator(){const [path,setPath]=useState([]);const [region,state,area]=path;const back=n=>setPath(path.slice(0,n));let content;
  if(!region) content=<><h2>Select a region of the United States</h2><div className="grid">{riskData.map(r=><button className="choice" onClick={()=>setPath([r])} key={r[0]}><b>{r[0]} ›</b><p>{r[1]}</p></button>)}</div></>;
  else if(!state) content=<><button className="back" onClick={()=>back(0)}>← USA</button><h2>{region[0]}</h2><p>{region[1]}</p><div className="grid">{region[2].map(s=><button className="choice" onClick={()=>setPath([region,s])} key={s[0]}><b>{s[0]} ›</b><div>{s[1].map((r,i)=><Badge key={i} risk={r}/>)}</div></button>)}</div></>;
  else if(!area) content=<><button className="back" onClick={()=>back(1)}>← {region[0]}</button><h2>{state[0]} risk profile</h2><RiskBars risks={state[1]}/><h3>Select a city</h3><div className="grid">{state[2].map(a=><button className="choice" onClick={()=>setPath([region,state,a])} key={a[0]}><b>{a[0]} ›</b><div>{a[2].map((r,i)=><Badge key={i} risk={r}/>)}</div></button>)}</div></>;
  else content=<><button className="back" onClick={()=>back(2)}>← {state[0]}</button><h2>{area[0]}, {state[0]}</h2><p>{area[1]}</p><RiskBars risks={area[2]}/></>;
  return <section className="panel navigator"><span className="eyebrow">Regional risk explorer</span><h1>Natural Disaster Risk Navigator</h1><p>Drill down from USA to a region, state, and city.</p><div className="crumbs">USA {region&&`› ${region[0]}`} {state&&`› ${state[0]}`} {area&&`› ${area[0]}`}</div>{content}</section>}
function RiskBars({risks}){const widths={Low:25,Moderate:50,High:75,Severe:100};return <div className="bars">{risks.map((r,i)=><div className="barrow" key={i}><span>{r[0]}</span><div className="bar"><i className={r[1].toLowerCase()} style={{width:`${widths[r[1]]}%`}}/></div><b>{r[1]}</b></div>)}</div>}
function Sales(){const [rows,setRows]=useState([['Jan',42000],['Feb',45500],['Mar',44200],['Apr',48900],['May',51200],['Jun',53800]]);const [periods,setPeriods]=useState(3);const [report,setReport]=useState(null);const change=(i,field,value)=>setRows(rows.map((r,n)=>n===i?[field==='period'?value:r[0],field==='value'?Number(value):r[1]]:r));
 const analyze=()=>{const growth=rows.slice(1).reduce((s,r,i)=>s+(r[1]-rows[i][1])/Math.max(rows[i][1],1),0)/(rows.length-1);const predictions=Array.from({length:periods},(_,i)=>{const v=Math.round(rows.at(-1)[1]*(1+growth)**(i+1));return {period:`Forecast ${i+1}`,value:v,low:Math.round(v*.91),high:Math.round(v*1.09)}});setReport({growth,predictions});};
 const doc=()=>{if(!report)return;const html=`<h1>Rudra AI Sales Trend Prediction</h1><p>Average growth: ${(report.growth*100).toFixed(1)}%</p><h2>Forecast</h2><ul>${report.predictions.map(p=>`<li>${p.period}: ${money(p.value)} (${money(p.low)}–${money(p.high)})</li>`).join('')}</ul>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'application/msword'}));a.download='rudra-ai-sales-report.doc';a.click();URL.revokeObjectURL(a.href)};
 return <section className="panel sales"><span className="eyebrow">Rudra AI analysis</span><h1>Sales Trend Predictor</h1><div className="sales-tabs"><b>Predictor</b>{report&&<b>Rudra AI Analysis</b>}</div><div className="data">{rows.map((r,i)=><div className="row" key={i}><input value={r[0]} onChange={e=>change(i,'period',e.target.value)}/><input type="number" value={r[1]} onChange={e=>change(i,'value',e.target.value)}/><button onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>×</button></div>)}</div><div className="actions"><button className="textbtn" onClick={()=>setRows([...rows,[`Period ${rows.length+1}`,0]])}>+ Add data point</button><label>Forecast <input type="number" min="1" max="12" value={periods} onChange={e=>setPeriods(+e.target.value)}/></label><button className="primary" onClick={analyze}>Analyze & predict</button></div>{report&&<div className="analysis"><h2>Forecast analysis</h2><p>Sales show an average {(report.growth*100).toFixed(1)}% period-over-period change.</p><div className="forecast">{report.predictions.map(p=><article key={p.period}><span>{p.period}</span><b>{money(p.value)}</b><small>{money(p.low)}–{money(p.high)}</small></article>)}</div><button className="primary" onClick={doc}>Analysis document</button></div>}</section>}
function App(){const [page,setPage]=useState('overview'),[region,setRegion]=useState('Northeast'),[weather,setWeather]=useState(null),[chat,setChat]=useState(false);const item=regions[region];useEffect(()=>{setWeather(null);fetch(`https://api.open-meteo.com/v1/forecast?latitude=${item.coords[0]}&longitude=${item.coords[1]}&current=temperature_2m&temperature_unit=fahrenheit`).then(r=>r.json()).then(x=>setWeather(Math.round(x.current.temperature_2m))).catch(()=>setWeather('--'))},[region]);
 const view=page==='overview'?<><section className="hero"><span className="eyebrow">Awareness starts local</span><h1>Know the risks.<br/>Plan the safer way.</h1><p>Regional weather and route awareness for safer everyday decisions.</p></section><section className="panel overview"><h2>Your regional snapshot</h2><select value={region} onChange={e=>setRegion(e.target.value)}>{Object.keys(regions).map(x=><option key={x}>{x}</option>)}</select><div className="weather">Current weather in {item.city}<b>{weather===null?'Loading…':`${weather}°`}</b></div><div className="cards"><article><span>Primary weather risk</span><h2>{item.weather}</h2><i style={{width:`${item.score}%`}}/><small>{item.score}/100 exposure</small></article><article><span>Road safety</span><h2>{item.road}</h2><i style={{width:`${Math.max(item.score-6,35)}%`}}/><small>Relative indicator</small></article><article><span>Best next step</span><h2>{item.action}</h2><small>Illustrative planning guidance</small></article></div></section></>:page==='prepare'?<section className="panel prepare"><h1>Prepare for any route</h1><p>Small habits make a meaningful difference when conditions shift.</p><ul><li>Check official forecasts and road conditions.</li><li>Share your route and arrival time.</li><li>Keep emergency essentials in your vehicle.</li><li>Give yourself extra time in severe weather.</li></ul></section>:page==='sales'?<Sales/>:<RiskNavigator/>;
 return <><header><div className="brand"><strong>R</strong> Regional Risk</div></header><nav><select value={page} onChange={e=>setPage(e.target.value)} aria-label="Open a Rudra AI section"><option value="overview">Overview</option><option value="prepare">Prepare</option><option value="sales">Sales AI</option><option value="navigator">Risk Explorer</option></select></nav><main>{view}</main><button className="chat" onClick={()=>setChat(!chat)}>● Ask Rudra AI</button>{chat&&<aside className="chatbox"><b>Rudra AI</b><p>Ask about your selected region, driving conditions, or preparedness.</p><input placeholder="Ask Rudra AI…"/></aside>}</>}
export default App;
